# Generated by Django 4.2.2 on 2023-06-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='TextModel',
        ),
    ]
